server:
  port: 8080

  # ???? ? default = 1800 (30?)
  servlet:
     session:
       timeout=90m:


spring:
  mustache:
    servlet:
      expose-request-attributes=true:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/adballoon
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver

    # ??? db??
    url: jdbc:mysql://127.0.0.1:3306/cap_ex?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  properties:
#    hibernate:
#      show_sql: true
#      ddl-auto: update
##      format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

